version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run: chmod +x ./mvnw 
      - run: ./mvnw -Dmaven.test.skip=true package
      - persist_to_workspace:
          root: ./
          paths:
            - target/

  test:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: chmod +x ./mvnw 
      - run: ./mvnw test

    deploy:
      docker:
        - image: circleci/openjdk:11
      steps:
        - add_ssh_keys:
            fingerprints:
              - "c8:d1:32:47:a7:13:6f:63:ba:4e:5c:3e:14:50:5a:77"
        - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./deploy_spring_boot.sh"

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
           - test

      - deploy:
          requires:
            - hold
          filters:
            branches:
              only:
                - master