version: 2.0

<<<<<<< HEAD
orbs:
  maven: circleci/maven@0.0.12
=======
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run: ./mvnw -Dmaven.test.skip=true package
      - persist_to_workspace:
         root: ./
         paths:
           - target/

  test:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: ./mvnw test
>>>>>>> 9cd42e3b541edf926ac4fc9d4b3bdb6def6b9b83

workflows:
  version: 2

  build-then-test:
    jobs:
<<<<<<< HEAD
      - maven/test # checkout, build, test, and upload test results
=======
      - build
      - test:
          requires:
            - build
>>>>>>> 9cd42e3b541edf926ac4fc9d4b3bdb6def6b9b83
